// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQvRMm6xkAwnaI2z4YDtmHEcecuP4-OSA',
    appId: '1:662756288481:web:cd318d27761c2c48cc14a0',
    messagingSenderId: '662756288481',
    projectId: 'estore-f2430',
    authDomain: 'estore-f2430.firebaseapp.com',
    storageBucket: 'estore-f2430.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBshh6-Zgt0A9EMNMNWciH4m8-R7KySIas',
    appId: '1:662756288481:android:37293def81e6c1e2cc14a0',
    messagingSenderId: '662756288481',
    projectId: 'estore-f2430',
    storageBucket: 'estore-f2430.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjnUaltEkBV3FOa7aKynrl9jWhNh47o8g',
    appId: '1:662756288481:ios:b32d446c6a062d5acc14a0',
    messagingSenderId: '662756288481',
    projectId: 'estore-f2430',
    storageBucket: 'estore-f2430.appspot.com',
    iosBundleId: 'com.example.cartCoralMachinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjnUaltEkBV3FOa7aKynrl9jWhNh47o8g',
    appId: '1:662756288481:ios:b32d446c6a062d5acc14a0',
    messagingSenderId: '662756288481',
    projectId: 'estore-f2430',
    storageBucket: 'estore-f2430.appspot.com',
    iosBundleId: 'com.example.cartCoralMachinetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQvRMm6xkAwnaI2z4YDtmHEcecuP4-OSA',
    appId: '1:662756288481:web:ff1d06757d5498b7cc14a0',
    messagingSenderId: '662756288481',
    projectId: 'estore-f2430',
    authDomain: 'estore-f2430.firebaseapp.com',
    storageBucket: 'estore-f2430.appspot.com',
  );
}
